#- name: Create a MongoDB repo
#  copy:
#    src: mongo.repo
#    dest: /etc/yum.repos.d/mongo.repo
- name: Create a MongoDB Repo
  shell: curl -s -o /etc/yum.repos.d/mongodb.repo https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path:  /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB service
  systemd:
    name: mongod
    state: started

- name: Download and Extract Frontend content
  include_role:
    name: common
    tasks_from: download

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users

#- name: Load Schema
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/{{item.name}}.js"
#    idempotent: "{{item.idempotency}}"
#  loop:
#    - {name: "catalogue", idempotency: yes}
#    - {name: "users", idempotency: yes}



#- name: Create a MongoDB repo
#  copy:
#    src: mongo.repo
#    dest: /etc/yum.repos.d/mongo.repo
#
#- name: Install MangoDB
#  ansible.builtin.yum:
#    name: mongodb-org
#    state: present
#
#- name: Update Liste IP address from 127.0.0.1 to 0.0.0.0 in config file
#  ansible.builtin.replace:
#    path: /etc/mongod.conf
#    regexp: '127.0.0.1'
#    replace: '0.0.0.0'
#
#- name: start MangoDB Services.
#  ansible.builtin.systemd:
#    name: mongod
#    state: started
#    enabled: yes
#
#- name: download and extract
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: download
#
#- name: cataloque schema loading for MongoDB commands with pseudo-idempotency
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/catalogue.js"
#    idempotent: yes
#
#- name: cataloque schema loading for MongoDB commands with pseudo-idempotency
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/users.js"
#    idempotent: yes
#
#
#
#
