- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com
#  tasks:
    - name: Print a play variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"

    - name: Print task Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.google.com

###when there is variable reference(Calling variable), Double quote it.

- name: Demo on Invenotry variables
  hosts: all
  tasks:
    - name: Print a variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"