- name: Install a package
  hosts: all
  become: yes
  ## Here all tasks run as root user
  tasks:
  yum:
    -name: install nodejs
     become: yes
     ## This makes only this task to run as root
     ansible.builtin.yum:
       name: nodejs
       state: present