- name : Demo on Tags
  hosts: localhost
  tasks:
   - name: ubuntu task
     ansible.builtin.debug:
       msg: Ubutun task
     tags:
       - Ubuntu
       - Debian

   - name: CentOS Task
     ansible.builtin.debug:
       msg: CentOS Task
     tags:
       - CentOS
       - Redhat
