- name: Roboshop Setup For FRONTEND
  hosts: FRONTEND
  become: yes
  tags: frontend
  roles:
   - name: frontend

- name: Roboshop Setup For MONGODB
  hosts: MONGODB
  become: yes
  tags: mongodb
  roles:
   - name: mongodb

- name: Roboshop Setup For CATALOQUE
  hosts: CATALOQUE
  become: yes
  tags: cataloque
  roles:
   - name: cataloque