- name: Roboshop Setup For FRONTEND
  hosts: FRONTEND
  become: yes
  tags: frontend
  roles:
   - name: frontend

- name: Roboshop Setup For MONGODB
  hosts: MONGODB
  become: yes
  tags: mongodb
  roles:
   - name: mongodb

- name: Roboshop Setup For CATALOGUE
  hosts: CATALOGUE
  become: yes
  tags: catalogue
  roles:
   - name: catalogue

- name: Roboshop Setup For REDIS
  hosts: REDIS
  become: yes
  tags: redis
  roles:
   - name: redis

- name: Roboshop Setup For USER
  hosts: USER
  become: yes
  tags: user
  roles:
   - name: user

- name: Roboshop Setup For CART
  hosts: CART
  become: yes
  tags: cart
  roles:
   - name: cart

- name: Roboshop Setup For MYSQL
  hosts: MYSQL
  become: yes
  tags: mysql
  roles:
   - name: mysql

- name: Roboshop Setup For SHIPPING
  hosts: SHIPPING
  become: yes
  tags: shipping
  roles:
   - name: shipping