- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: copy the extracted content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Update Main Nginx Config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

# this example copy is for files, but it doesn't support for multi-env
#- name: copy roboshop configuration file
#  copy:
#    src: roboshop.conf
#    dest: /etc/nginx/default.d/roboshop.conf

- name: Update roboshop configuration file
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  when: COMPONENT is not defined

- name: Update roboshop configuration file
  template:
    src: roboshop-lb.conf
    dest: /etc/nginx/default.d/roboshop.conf
  when: COMPONENT is defined

- name: Install Node Exporter
  ansible.builtin.include_role:
    name: common
    tasks_from: node-exporter

- name: Install File Beat
  ansible.builtin.include_role:
    name: common
    tasks_from: filebeat
  vars:
    LOG_FILE: /var/log/nginx/access.log
    STRUCTURED: "false"

- name: restart Nginx Service
  systemd:
    name: nginx
    enabled: yes
    state: restarted
  ignore_errors: yes
