- name: Setup MySQL Repo
  shell: curl -s -L -o /etc/yum.repos.d/mysql.repo https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo

- name: Install MySQL Server
  yum:
    name: [ "mysql-community-server", "MySQL-python" ]
    state: present

- name: Start MySQL Service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the default password
  community.mysql.mysql_query:
    query: show databases
    login_password: RoboShop@1
    login_user: root
  register: default_mysql_check
  ignore_errors: yes

#- name: Check the default password
#  shell: echo "show databases;" | mysql -uroot -pRoboShop@1
#  register: default_mysql_check
#  ignore_errors: yes

- name: Grab default password
  when: default_mysql_check.failed
  shell: grep 'A temporary password' /var/log/mysqld.log  | awk '{print $NF}'
  register: out

- name: Reset MySQL Password
  when: default_mysql_check.failed
  shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';" | mysql --connect-expired-password -uroot -p"{{out.stdout}}"

- name: Uninstall Validate Password Plugin
  community.mysql.mysql_query:
    query: uninstall plugin validate_password
    login_password: RoboShop@1
    login_user: root
  ignore_errors: yes

- name: Download and Extract Frontend content
  include_role:
    name: common
    tasks_from: download

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: RoboShop@1


#- name: Install MySQL
#  yum:
#    name: [ "mysql-community-server" ]
#    state: present
#
#- name: start MySQL services
#  systemd:
#    name: mysqld
#    state: started
#    enabled: yes
#
#- name: Check the Default Password
#  community.mysql.mysql_query:
#    query: show databases
#    login_user: root
#    login_password: RoboShop@1
#  register: default_mysql_check
#  ignore_errors: yes
#
##- name: Check the Default password
##  shell: echo "show databases;" | mysql -uroot -pRoboShop@1
##  register: default_mysql_check
##  ignore_errors: yes
#
##- name: Print
##  debug:
##    msg: "{{default_mysql_check}}"
#
#- name: Grab Default MySQL Password
#  when: default_mysql_check.failed
#  shell: grep 'A temporary password' /var/log/mysqld.log  | awk '{print $NF}'
#  register: out
#
#- name: Reset MySQL password
#  when: default_mysql_check.failed
#  shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';" | mysql --connect-expired-password -uroot -p"{{out.stdout}}"
#
#- name: uninstall plugin validate_password
#  community.mysql.mysql_query:
#    query: uninstall plugin validate_password
#    login_user: root
#    login_password: RoboShop@1
#  ignore_errors: yes
#
#- name: download and extract
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: download
#
#- name: Load Schema
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /tmp/mysql-main/shipping.sql
#    login_user: root
#    login_password: RoboShop@1
#
#
#
