- name: Setup MySQL Repo
  shell: curl -s -L -o /etc/yum.repos.d/mysql.repo https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo

- name: Install MySQL
  yum:
    name: [ "mysql-community-server" ]
    state: present

- name: start MySQL services
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the Default password
  shell: echo "show databases;" | mysql -uroot -pRoboShop@1
  register: default_mysql_check
  ignore_errors: yes

- name: Grab Default MySQL Password
  shell: grep 'A temporary password' /var/log/mysqld.log  | awk '{print $NF}'
  register: out





