- name: Download from GitHub
  ansible.builtin.include_tasks:
    file: download-from-github.yml

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: Delete Old App Code
  file:
    path: /home/roboshop/{{COMPONENT}}/
    state: absent

- name: copy the extracted content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop