- name: Install NodeJS Repos Script
  shell: curl -sL https://rpm.nodesource.com/setup_lts.x | sudo bash

- name: Install NodeJS
  yum:
    name: [ "nodejs" ]
    state: present

- name: Download from GitHub
  ansible.builtin.include_tasks:
    file: download.yml

- name: Install {{COMPONENT}} Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop

- name: Setup SystemD
  ansible.builtin.include_tasks:
    file: setup-systemd.yml

- name: Install node_exporter
  ansible.builtin.include_tasks:
    file: node-exporter.yml

- name: Install File Beat
  ansible.builtin.include_tasks:
    file: filebeat.yml
  vars:
    LOG_FILE: /var/log/{{COMPONENT}}.log
