-name: Install NodeJS
 ansible.builtin.yum:
   name: ["nodejs", "make", "gcc-c++"]
   state: present

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop

- name: Download from GitHub
  ansible.builtin.include_tasks:
    file: download-from-github.yml

- name: copy the extracted content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    become_user: roboshop






#$ cd /home/roboshop
#$ unzip /tmp/catalogue.zip
#$ mv catalogue-main catalogue
#$ cd /home/roboshop/catalogue
#$ npm install
#NOTE: We need to update the IP address of MONGODB Server in systemd.service file. Replace MONGO_DNSNAME with IP address.
#Now, lets set up the service with systemctl.
#
## mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
## systemctl daemon-reload
## systemctl start catalogue
## systemctl enable catalogue