- name: Install NodeJS
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop

- name: Download from GitHub
  ansible.builtin.include_tasks:
    file: download.yml

- name: copy the extracted content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install Cataloque Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
    state: present
    become_user: roboshop
