- name: update SystemD Configuratin.
  ##copy:   ##Files replace by template to support multi-environemt like DeV and Prod.
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
  notify: Restart service - Handlers

- name: Restart {{COMPONENT}} service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
